apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway-service
  labels:
    app: gateway-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: USER_SERVICE_URL
              value: {{ .Values.env.USER_SERVICE_URL }}
            - name: PRODUCT_SERVICE_URL
              value: {{ .Values.env.PRODUCT_SERVICE_URL }}
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}